const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const matrixRouter = require('./matrixRouter')
const newsRouter = require('./newsRouter')
const partnerRouter = require('./partnerRouter')
const walletRouter = require('./walletRouter')
const StarRouter = require('./starRouter')
const GameRouter = require('./gameRouter')
const InvestRouter = require('./InvestRouter')
const CasinoRouter = require('./casinoRouter')
const MarketRouter = require('./marketRouter')
const OrderRouter = require('./orderRouter')
const ChartRouter = require('./chartRouter')
const ExchangeHistoryRouter = require('./exchangeHistoryRouter')
const settingsRouter = require('./settingsRouter')

   
router.use('/user', userRouter)
router.use('/matrix', matrixRouter) 
router.use('/news', newsRouter)
router.use('/structure', partnerRouter)
router.use('/wallet', walletRouter)
router.use('/tinkoff', walletRouter)
router.use('/star-trek', StarRouter)
router.use('/', StarRouter)
router.use('/v2', InvestRouter)
router.use('/fullstate', GameRouter)
router.use('/casino', CasinoRouter)
router.use('/marketslist', MarketRouter)
router.use('/orders', OrderRouter)
router.use('/charts', ChartRouter)
router.use('/trade-history', ExchangeHistoryRouter)
router.use('/settings', settingsRouter)
router.use('/registration', settingsRouter)



module.exports = router 